### ISSUE TITLE
Remote version file missing

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/StockDefaultSettings#1]
![image](https://user-images.githubusercontent.com/1559108/96182666-680a0780-0efb-11eb-807d-029a1c6a4b15.png)

@linuxgurugamer 

http://ksp.spacetux.net/avc/StockDefaultSettings

It just says "End of the line".

**Comment by HebaruSan** [comment]
Maybe it should be HTTP**S**?

**Comment by linuxgurugamer** [comment]
I haven't uploaded it yet, will do it later this evening

**Comment by linuxgurugamer** [comment]
Just uploaded it, let me know if it's still having issues

**Comment by HebaruSan** [comment]
Confirmed, the error is gone in the latest bot pass. Thanks!
